russian = {'WindowTitle': 'USB Шпион - Сервер',
            'StatusGroup': 'Статус',
            'StatusLabel': 'Сервер запущен на IPv4:{0} Port:<b>{1}</b>.',
            'TrayClose': 'Программа продолжит работать в системном трее.\nЧтобы завершить программу, выбирите "Выход" в\nконтекстном меню в системном трее.',
            'SettingsGroup': 'Настройки',
            'Duration': 'Продолжительность:',
            'DurationSuffix': ' секунд',
            'Duration2': 'Установите продолжительность сообщения от 5 до 60 секунд\n(Некоторые системы могут игнорировать данный параметр)',
            'Language': 'Язык:',
            'UserGroup': 'Список пользователей',
            'UserToolTip': 'Отображает список пользователей с подключёнными USB-флеш-накопителями',
            'Close': 'Закрыть',
            'Save': 'Сохранить',
            'Minimize': 'Свернуть',
            'Restore': 'Развернуть',
            'Quit': 'Выйти',
            'errAtStartName': 'Ошибка в конфигурации',
            'ErrAtStart': 'Файл "config.xml" был повреждём или некорректно изменён.\nПерезапустите программу, что бы восстановить файл.',
            'ClientName': 'Клиент: {0} ({1})',
            'ClientMessageIN': '{0} с S/N: {1} \nбыла подключена.',
            'ClientMessageOUT': '{0} с S/N: {1} \nбыла отключена.',
            'Notification': 'Отключить уведомления:',
            'SecondTitle': 'Выберите сетевой интерфейс',
            'InterfacesList': 'Имя: {0}, IP: {1}, MAC: {2}',
            'warnInts': 'Ни один интерфейс не выбран.',
            'cancelInts': 'Выберите интерфейс и нажмите "OK", чтобы продолжить.',
            'msgBoxPortTitle': 'Недопустимый порт',
            'msgBoxPortText': 'Введите порт от 0 до 65535:',
            'msgBoxIPv4Title': 'Недопустимый IPv4-адрес',
            'msgBoxIPv4Text': 'Введите ваш локальный IPv4-адрес:'}

english = {'WindowTitle': 'USB Spy - Server',
            'StatusGroup': 'Status',
            'StatusLabel': 'The server is running on IPv4:{0}  port:<b>{1}</b>.',
            'TrayClose': 'The program will keep running in the system tray. To\nterminate the program, choose "Quit" in the\ncontext menu of the system tray entry.',
            'SettingsGroup': 'Settings',
            'Duration': 'Duration:',
            'DurationSuffix': ' seconds',
            'Duration2': 'Set message duration from 5 to 60 seconds\n(Some system may ignore this)',
            'Language': 'Language:',
            'UserGroup': 'Current users list',
            'UserToolTip': 'Shows users with plugged in USB flash drives',
            'Close': 'Close',
            'Save': 'Save',
            'Minimize': 'Minimize',
            'Restore': 'Restore',
            'Quit': 'Quit',
            'errAtStartName': 'Error in configuration',
            'ErrAtStart': 'File "config.xml" was сorrupt or incorrectly modified\nPlease, restart application to restore the file.',
            'ClientName': 'Client: {0} ({1})',
            'ClientMessageIN': '{0} with S/N: {1} \nwas plugged in .',
            'ClientMessageOUT': '{0} with S/N: {1} \nwas plugged out.',
            'Notification': 'Disable notifications:',
            'SecondTitle': 'Choose network interface',
            'InterfacesList': 'Name: {0}, IP: {1}, MAC: {2}',
            'warnInts': 'No interface is selected.',
            'cancelInts': 'Select the interface and click "OK" to continue.',
            'msgBoxPortTitle': 'Unacceptable port',
            'msgBoxPortText': 'Enter port from 0 to 65535:',
            'msgBoxIPv4Title': 'Unacceptable IPv4 address',
            'msgBoxIPv4Text': 'Enter your local IPv4 address:'}

ukrainian = {'WindowTitle': 'USB Шпигун - Сервер',
            'StatusGroup': 'Статус',
            'StatusLabel': 'Сервер запущенний на IPv4:{0} Port:<b>{1}</b>.',
            'TrayClose': 'Програма продовжить працювати в системному треї.\nЩоб завершити програму, оберіть "Вихід" в\nконтекстному меню в системному треї.',
            'SettingsGroup': 'Налаштування:',
            'Duration': 'Тривалість:',
            'DurationSuffix': ' секунд',
            'Duration2': 'Встановіть тривалість повідомлення від 5 до 60 секунд\n(Деякі системи можуть ігнорувати даний параметр)',
            'Language': 'Мова:',
            'UserGroup': 'Список користувачів',
            'UserToolTip': 'Показує список користувачів з підключеними USB-флеш-накопичувачами',
            'Close': 'Закрити',
            'Save': 'Зберегти',
            'Minimize': 'Згорнути',
            'Restore': 'Розгорнути',
            'Quit': 'Вийти',
            'errAtStartName': 'Помилка в конфігурації',
            'ErrAtStart': 'Файл "config.xml" був пошкоджений або некоректно змінений.\nПерезапустіть програму, що б відновити файл.',
            'ClientName': 'Клієнт: {0} ({1})',
            'ClientMessageIN': '{0} з S/N: {1} \nбула підключена.',
            'ClientMessageOUT': '{0} з S/N: {1} \nбула відключена.',
            'Notification': 'Вимкнути сповіщення:',
            'SecondTitle': 'Виберіть мережевий інтерфейс',
            'InterfacesList': 'Iм\'я: {0}, IP: {1}, MAC: {2}',
            'warnInts': 'Жоден інтерфейс не обраний.',
            'cancelInts': 'Виберіть інтерфейс і натисніть "OK", щоб продовжити.',
            'msgBoxPortTitle': 'Неприпустимий порт',
            'msgBoxPortText': 'Введiть порт з 0 до 65535:',
            'msgBoxIPv4Title': 'Неприпустимий IPv4-адрес',
            'msgBoxIPv4Text': 'Введіть свій локальний IPv4-адрес:'}
